### ISSUE TITLE
The side effect of "Recent Activity" being hidden also prevents you from terminating sessions

### ISSUE THREAD

**Issue by quackbox** [roblox-dev-forum/hide-email#4]
I'm guessing this part of the side effect was overlooked. Recent activity includes the interface to sign out of all sessions.

I thought signing out of all sessions on www.roblox.com would terminate the devforum session too as the SSO provider, but it doesn't.

If your roblox account is compromised, the attacker can login to the devforum and gain persistent access. You can't terminate their session, so either it'll have to expire or the attacker will have to logout.

Maybe it's worth reconsidering whether the side effect is still acceptable given the security feature you lose (if this hasn't been considered already).

Cheers 🙂

**Comment by buildthomas** [comment]
They're going to solve this one differently
